---
title: "社會科學院"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: css/style.css
    includes:
      in_header: header.html
    self_contained: FALSE
params:
  gsEventID: "1Ampe6kDzKomv4-YlOW0HZwxlUyCVZygQMg_1F3pn4Io"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,eval=T)

library(flexdashboard); library(htmltools); library(stringr)
source("/Users/martin/Desktop/GitHub/My-functions/DataScienceTeaching/R/apiResources.R")
source("/Users/martin/Desktop/GitHub/NTPUSOC/Lobby_dashboard/usrwebcrawl.R")
library(htmltools); library(rlang); library(googlesheets); library(lubridate)
gs_auth()
params$gsEventID %>%
  gs_key %>%
  gs_read(ws="Form Responses 1") -> eventDF
eventDF %>%
  mutate(
    日期=mdy(日期)
  ) %>% 
  arrange(日期) -> eventDF
```


```{css css}
.centerimg { 
    position: absolute;
    left: 0;
    top: 20;
    height: 100%;
    width: 100%;
}
.hero {
  align-items: center;
  height: auto;
  min-width: 0;
}

img2 {
  width: 450px;
  max-width: 100%;
  max-height: 351px;
}

#latestEvents > .chart-title {
    background-color: #e36851;
    color: white;
}
#USR > .chart-title {
    color: #ffffff;
    background-color: #28a745;
}

/* 移除navigation bar */

body {
  padding-top: 0px
}

.navbar{
  visibility: hidden
}

#qrcode {
  width:160px;
  height:160px;
  margin-top:15px;
}
```




社科院訊息
====


USR新聞 {data-width=300}
-----------------------------------------------------------------------

### <i class="fas fa-hands-helping"></i> USR 園地 {#USR}

```{r}
"http://usrsoc.ntpu.edu.tw/news.html" %>%
  usrwebcrawl %>% usrnewsCard
```

近期活動  {data-width=400}
-----------------------------------------------------------------------

### <i class="fa fa-calendar" aria-hidden="true"></i> 近期活動 {#latestEvents}

```{r}
source("/Users/martin/Desktop/GitHub/NTPUSOC/Lobby_dashboard/R/events.R")
event_schedule(eventDF)  -> html_eventSchedule
html_eventSchedule %>%
  {eval(parse(text=.))}
```


Column {data-width=300}
-----------------------------------------------------------------------

### 你的訊息QR 

```{r, eval=FALSE}
div(id="qrcode")
```



```{r,eval=F,echo=F}
"https://www.facebook.com/usrsocntpu/posts/320250995487704" %>%
  bitlyRequest() 
```

### 互動看板使用方法

1. 用手按壓你有興趣的訊息。

2. 看板「你的訊息QR」區塊會出現對應QRcode。

3. 拿起你的手機掃瞄QRcode即可回去慢慢享用。

```{r }
HTML('
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">請掃此QR code取得你有興趣的訊息</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-qrcode">    
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
      </div>
    </div>
  </div>
</div>   
')
 
```

```{js modal timeout}
$(function(){
    $('#exampleModal').on('show.bs.modal', function(){
        var myModal = $(this);
        clearTimeout(myModal.data('hideInterval'));
        myModal.data('hideInterval', setTimeout(function(){
            myModal.modal('hide');
        }, 3000));
    });
});
```

```{js js postqr2modal}
function postqr2modal(url){
document.getElementById("modal-qrcode").innerHTML=""; 
new QRCode(document.getElementById("modal-qrcode"), url);

}
```

