---
title: "Lobby_dashboard"
author: "林茂廷"
date: "12/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr); library(dplyr); library(purrr); library(stringr); library(lubridate); library(tidyr); 
```

## accuweather

###  Search Taiwan Location Info

```{r}
.accuweatherAPI<-Sys.getenv("accuweatherAPI")
"adminareas/tw" %>%
    paste0("http://dataservice.accuweather.com/locations/v1/",.) %>%
GET(
  query = list(apikey = .accuweatherAPI)
  ) %>%
  content() -> TWInfo
```

http://dataservice.accuweather.com/locations/v1/countries/

```{r}
.accuweatherAPI<-Sys.getenv("accuweatherAPI")
"2515397" %>%
    paste0("http://dataservice.accuweather.com/currentconditions/v1/",.) %>%
GET(
  query = list(apikey = .accuweatherAPI)
  ) %>%
  content() -> NewTaipeiCityInfo
```



```{r}
.accuweatherAPI<-Sys.getenv("accuweatherAPI")
GET("http://dataservice.accuweather.com/locations/v1", path="cities/autocomplete",
query = list(apikey = .accuweatherAPI )) %>%
  content() 
```
